// <auto-generated />
namespace WebApp.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddcolumnAmountinOrderDetailtable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddcolumnAmountinOrderDetailtable));
        
        string IMigrationMetadata.Id
        {
            get { return "201812020832587_Add column Amount in OrderDetail table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
