// <auto-generated />
namespace WebApp.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddcolumnIdinOrderDetailandsetPrimaryKeyforId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddcolumnIdinOrderDetailandsetPrimaryKeyforId));
        
        string IMigrationMetadata.Id
        {
            get { return "201812040221284_Add column Id in OrderDetail and set Primary Key for Id"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
